import { StyleSheet } from 'react-native';

// 앱 전체 화면과 컴포넌트가 공유하는 스타일입니다.
// 기능별 컴포넌트는 이 파일의 styles를 import해서 같은 UI 톤을 유지합니다.
export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f7fbf9' },
  keyboardAvoidingRoot: { flex: 1 },
  screen: { flexGrow: 1, paddingHorizontal: 18, paddingBottom: 26, paddingTop: 12 },
  briefingScreen: { paddingBottom: 32 },
  pressedFeedback: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  kicker: { color: '#279b64', fontSize: 12, fontWeight: '900', letterSpacing: 0, marginBottom: 5 },
  title: { color: '#141821', flexShrink: 1, fontSize: 29, fontWeight: '900' },
  homeHeader: { gap: 3 },
  homeTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 9 },
  homeTitleGroup: { flex: 1, minWidth: 0 },
  homeTitleButton: { flex: 1, minWidth: 0 },
  homeTitleInline: { alignItems: 'center', flexDirection: 'row', minWidth: 0 },
  homeTitleChevron: { marginLeft: 3, marginTop: 5, opacity: 0.85 },
  homeBasisText: { color: '#687180', fontSize: 12, fontWeight: '900', lineHeight: 18, marginTop: 0 },
  regionSwitchButton: { alignItems: 'center', justifyContent: 'center', minHeight: 34, minWidth: 34 },
  regionSwitchText: { color: '#687180', fontSize: 23, fontWeight: '900' },
  regionAddButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, elevation: 1, flexDirection: 'row', gap: 4, justifyContent: 'center', minHeight: 36, paddingHorizontal: 11, shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 8 },
  regionAddIcon: { color: '#687180', fontSize: 15, fontWeight: '900', lineHeight: 16 },
  regionAddText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  homeWeatherIconWrap: { alignItems: 'center', height: 36, justifyContent: 'center', marginLeft: 'auto', width: 34 },
  homeWeatherChip: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, elevation: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', marginLeft: 'auto', minHeight: 36, paddingHorizontal: 9, shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 8 },
  homeWeatherValue: { color: '#141821', fontSize: 12, fontWeight: '900', lineHeight: 14 },
  homeWeatherLabel: { color: '#687180', fontSize: 9, fontWeight: '900', lineHeight: 11 },
  homeGpsButton: { alignItems: 'center', backgroundColor: '#f8f9fa', borderRadius: 8, borderWidth: 1, height: 32, justifyContent: 'center', width: 34 },
  homeGpsButtonDisabled: { opacity: 0.45 },
  homeGpsIcon: { color: '#687180', fontSize: 23, fontWeight: '900', lineHeight: 25 },
  favoritePicker: { backgroundColor: '#ffffff', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1.2, marginTop: 10, padding: 12 },
  favoritePickerTitle: { color: '#687180', fontSize: 12, fontWeight: '900' },
  favoritePickerList: { gap: 8, marginTop: 10 },
  favoritePickerItem: { alignItems: 'center', backgroundColor: '#f7faf8', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 9 },
  favoritePickerSelectArea: { flex: 1, paddingVertical: 4 },
  favoritePickerRemoveButton: { alignItems: 'center', borderColor: '#c5ccd6', borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 32, paddingHorizontal: 10 },
  favoritePickerText: { color: '#141821', fontSize: 14, fontWeight: '900' },
  favoritePickerTextActive: { color: '#141821' },
  gpsRegionButton: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, marginTop: 10, paddingHorizontal: 12, paddingVertical: 10 },
  gpsRegionButtonIcon: { alignItems: 'center', backgroundColor: '#eef1f5', borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  gpsRegionButtonIconText: { color: '#687180', fontSize: 19, fontWeight: '900', lineHeight: 21 },
  gpsRegionButtonBody: { flex: 1 },
  gpsRegionButtonLabel: { color: '#8a94a3', fontSize: 10, fontWeight: '900', marginBottom: 2 },
  gpsRegionButtonText: { color: '#141821', fontSize: 14, fontWeight: '900' },
  homeRegionSearchPanel: { backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, marginTop: 10, padding: 12 },
  homeRegionSearchInputRow: { alignItems: 'center', backgroundColor: '#f8f9fa', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', marginTop: 10, minHeight: 44 },
  homeRegionSearchInput: { color: '#141821', flex: 1, fontSize: 14, fontWeight: '800', minHeight: 44, paddingHorizontal: 12, paddingVertical: 0 },
  homeRegionSearchGpsButton: { alignItems: 'center', borderLeftColor: '#d9dee5', borderLeftWidth: 1, height: 38, justifyContent: 'center', marginRight: 4, width: 44 },
  homeRegionSearchEmpty: { color: '#8a94a3', fontSize: 12, fontWeight: '800', lineHeight: 18, marginTop: 10 },
  homeRegionSuggestionList: { gap: 8, marginTop: 10 },
  homeRegionSuggestionItem: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 11 },
  homeRegionSuggestionTextGroup: { flex: 1, paddingVertical: 2 },
  homeRegionSuggestionTitle: { color: '#141821', fontSize: 14, fontWeight: '900' },
  homeRegionSuggestionMeta: { color: '#687180', fontSize: 11, fontWeight: '800', lineHeight: 16, marginTop: 3 },
  homeRegionSuggestionStarButton: { alignItems: 'center', height: 38, justifyContent: 'center', width: 38 },
  homeRegionSuggestionStar: { color: '#aab4ae', fontSize: 23, fontWeight: '900', lineHeight: 25 },
  homeRegionSuggestionStarActive: { color: '#e2b93b' },
  dataRegionPicker: { backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, marginTop: 10, padding: 12 },
  dataRegionQuickGrid: { flexDirection: 'row', gap: 8, marginTop: 10 },
  dataRegionQuickItem: { backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flex: 1, paddingHorizontal: 11, paddingVertical: 10 },
  dataRegionQuickLabel: { color: '#8a94a3', fontSize: 10, fontWeight: '900', marginBottom: 3 },
  dataRegionQuickTitle: { color: '#141821', fontSize: 13, fontWeight: '900' },
  dataRegionFavoriteList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  dataRegionFavoriteItem: { backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8 },
  dataRegionFavoriteText: { color: '#141821', fontSize: 12, fontWeight: '900' },
  regionLoadingOverlay: { alignItems: 'center', bottom: 78, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0, zIndex: 10 },
  regionLoadingCard: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.96)', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1.2, minWidth: 220, paddingHorizontal: 22, paddingVertical: 18, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.12, shadowRadius: 18 },
  regionLoadingTitle: { color: '#141821', fontSize: 17, fontWeight: '900', marginTop: 10 },
  regionLoadingText: { color: '#687180', fontSize: 12, fontWeight: '800', marginTop: 5 },
  detailScreenHeader: { alignItems: 'center', flexDirection: 'row', gap: 12, marginBottom: 10, paddingTop: 2 },
  detailBackButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1.2, height: 38, justifyContent: 'center', shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.06, shadowRadius: 8, width: 38 },
  detailHeaderTextGroup: { flex: 1, minWidth: 0 },
  detailHeaderSubText: { color: '#687180', fontSize: 13, fontWeight: '900', marginTop: 5 },
  detailFlowButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, elevation: 2, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, minHeight: 56, paddingHorizontal: 14, paddingVertical: 10, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  detailFlowButtonTextGroup: { flex: 1, minWidth: 0 },
  detailFlowButtonText: { fontSize: 13, fontWeight: '900', lineHeight: 18 },
  detailFlowButtonHint: { color: '#687180', fontSize: 10, fontWeight: '800', lineHeight: 14, marginTop: 1 },
  detailFlowButtonArrow: { fontSize: 22, fontWeight: '800', lineHeight: 24 },
  homeMapPreviewCard: { backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, elevation: 2, marginTop: 14, overflow: 'hidden', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  homeMapPreviewHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 14, paddingTop: 13 },
  homeMapPreviewTitleGroup: { flex: 1, minWidth: 0, paddingRight: 10 },
  homeMapPreviewTitle: { color: '#141821', fontSize: 15, fontWeight: '900' },
  homeMapPreviewSubtitle: { color: '#687180', fontSize: 11, fontWeight: '800', lineHeight: 16, marginTop: 3 },
  homeMapPreviewIconButton: { alignItems: 'center', borderRadius: 999, height: 34, justifyContent: 'center', width: 34 },
  homeMapPreviewFrame: { backgroundColor: '#edf2f0', borderColor: '#eef1f5', borderRadius: 8, borderWidth: 1, height: 178, marginHorizontal: 14, marginTop: 12, overflow: 'hidden' },
  homeMapPreviewWebView: { backgroundColor: '#edf2f0', flex: 1 },
  homeMapPreviewFooter: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 44, paddingHorizontal: 14 },
  homeMapPreviewLink: { fontSize: 13, fontWeight: '900' },
  statusCard: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 0,
    marginTop: 6,
    paddingHorizontal: 4,
    paddingVertical: 4,
    elevation: 0,
    shadowColor: '#141821',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  dataSummaryCard: {
    backgroundColor: '#f8fffb',
    borderRadius: 8,
    borderWidth: 1.5,
    marginTop: 20,
    padding: 18,
  },
  statusHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between', paddingHorizontal: 2 },
  statusTitleGroup: { flex: 1 },
  statusEyebrow: { color: '#279b64', fontSize: 11, fontWeight: '900', marginBottom: 6 },
  statusRegion: { color: '#141821', fontSize: 17, fontWeight: '900', lineHeight: 23 },
  statusDate: { color: '#687180', fontSize: 12, fontWeight: '800', lineHeight: 18, marginTop: 2 },
  gradeBadge: { borderRadius: 999, color: '#ffffff', fontSize: 15, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 17, paddingVertical: 10 },
  weatherBadge: { alignItems: 'center', justifyContent: 'center', minHeight: 28, minWidth: 28 },
  weatherIcon: { color: '#f3b43f', fontSize: 25, fontWeight: '900', lineHeight: 28 },
  weatherText: { color: '#687180', fontSize: 11, fontWeight: '900' },
  currentValueRow: { alignItems: 'flex-end', flexDirection: 'row', gap: 12, marginTop: 34 },
  currentValue: { color: '#141821', fontSize: 74, fontWeight: '900' },
  currentUnit: { color: '#687180', fontSize: 18, fontWeight: '900', marginBottom: 17 },
  statusGaugeDisk: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    elevation: 4,
    height: 182,
    justifyContent: 'center',
    marginTop: 4,
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    width: 182,
  },
  metricGaugeCarousel: { marginHorizontal: -10, marginTop: 2, minHeight: 218, overflow: 'visible' },
  metricGaugePage: { alignItems: 'center', justifyContent: 'center', minHeight: 218, paddingBottom: 10 },
  metricGaugeSlot: { alignItems: 'center', justifyContent: 'center' },
  metricGaugeSlotActive: { marginHorizontal: -2, zIndex: 2 },
  metricGaugeSlotSide: { marginTop: 92, opacity: 0.98, position: 'absolute', zIndex: 1 },
  metricGaugeSlotLeft: { left: 10 },
  metricGaugeSlotRight: { right: 10 },
  statusGaugeWrap: { alignItems: 'center', height: 168, justifyContent: 'center', width: 168 },
  statusGaugeCenter: { alignItems: 'center', bottom: 0, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0 },
  statusGaugeLabel: { color: '#687180', fontSize: 11, fontWeight: '900', marginBottom: 2 },
  statusGaugeValue: { color: '#141821', fontSize: 47, fontWeight: '900', lineHeight: 52 },
  statusGaugeUnit: { color: '#8a94a3', fontSize: 10, fontWeight: '900', lineHeight: 12, marginTop: -2 },
  statusGaugeGrade: { fontSize: 13, fontWeight: '900', marginTop: 1 },
  statusSideGaugeDisk: { alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 999, elevation: 3, height: 90, justifyContent: 'center', shadowColor: '#64748b', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18, width: 90 },
  statusSideGaugeWrap: { alignItems: 'center', height: 78, justifyContent: 'center', width: 78 },
  statusSideGaugeCenter: { alignItems: 'center', bottom: 0, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0 },
  statusSideGaugeLabel: { color: '#687180', fontSize: 9, fontWeight: '900', marginBottom: 1 },
  statusSideGaugeValue: { color: '#141821', fontSize: 19, fontWeight: '900', lineHeight: 23 },
  statusSideGaugeGrade: { fontSize: 9, fontWeight: '900', marginTop: 1 },
  statusGaugeMetaRow: { alignItems: 'center', flexDirection: 'row', gap: 7, justifyContent: 'center', marginTop: 6 },
  statusGaugeMetaPill: { backgroundColor: '#eef1f5', borderRadius: 999, color: '#687180', fontSize: 10, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 4 },
  statusSummary: { color: '#687180', fontSize: 16, lineHeight: 25, marginTop: 14, textAlign: 'center' },
  detailRegionSelector: { alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1.2, elevation: 2, flexDirection: 'row', gap: 12, justifyContent: 'space-between', marginTop: 14, paddingHorizontal: 13, paddingVertical: 12, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  detailRegionSelectorLabel: { color: '#8a94a3', fontSize: 11, fontWeight: '900', marginBottom: 3 },
  detailRegionTitle: { color: '#141821', fontSize: 18, fontWeight: '900' },
  detailRegionSelectorIconWrap: { alignItems: 'center', backgroundColor: '#f8f9fa', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 34, justifyContent: 'center', width: 34 },
  noticeText: { color: '#279b64', fontSize: 13, fontWeight: '700', lineHeight: 19, marginTop: 10 },
  metricGrid: { backgroundColor: 'transparent', borderRadius: 8, borderWidth: 0, flexDirection: 'row', gap: 10, marginTop: 14, padding: 0 },
  metricPill: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderTopWidth: 4, borderWidth: 1, elevation: 1, flex: 1, minHeight: 142, paddingHorizontal: 8, paddingVertical: 13, shadowColor: '#141821', shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.05, shadowRadius: 12 },
  metricLabel: { color: '#687180', fontSize: 11, fontWeight: '800', textAlign: 'center' },
  metricCode: { color: '#279b64', fontSize: 11, fontWeight: '900', marginTop: 4 },
  metricValue: { color: '#141821', fontSize: 24, fontWeight: '900', marginTop: 8 },
  metricUnit: { color: '#687180', fontSize: 11, marginTop: 2 },
  metricMiniTrack: { backgroundColor: '#eef1f5', borderRadius: 999, height: 6, marginTop: 10, overflow: 'hidden', width: '100%' },
  metricMiniFill: { borderRadius: 999, height: '100%' },
  metricGrade: { fontSize: 12, fontWeight: '900', marginTop: 8 },
  activityGuideCard: { backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, elevation: 2, marginTop: 14, padding: 14, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  activityGuideHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 10, justifyContent: 'space-between', marginBottom: 10 },
  activityGuideHeaderTitleGroup: { flex: 1, minWidth: 0 },
  activityGuideEditButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 34, justifyContent: 'center', width: 34 },
  activityGuideTitle: { color: '#141821', fontSize: 18, fontWeight: '900' },
  activityGuideSummary: { color: '#687180', fontSize: 12, fontWeight: '800', lineHeight: 18, marginTop: 4 },
  activityGuideList: { gap: 2 },
  activityGuideRow: { alignItems: 'center', borderTopColor: '#eef1f5', borderTopWidth: 1, flexDirection: 'row', gap: 10, minHeight: 58, paddingVertical: 9 },
  activityGuideIconBox: { alignItems: 'center', borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  activityGuideTextGroup: { flex: 1, minWidth: 0 },
  activityGuideRowTitle: { color: '#141821', fontSize: 13, fontWeight: '900' },
  activityGuideRowLocation: { color: '#3f6f9f', fontSize: 11, fontWeight: '900', lineHeight: 15, marginTop: 2 },
  activityGuideRowDesc: { color: '#687180', fontSize: 11, fontWeight: '800', lineHeight: 16, marginTop: 3 },
  activityGuideBadge: { borderRadius: 999, fontSize: 11, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 5 },
  activityGuideRemoveButton: { alignItems: 'center', backgroundColor: '#f8f9fa', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 28, justifyContent: 'center', width: 28 },
  activityGuideEmptyBox: { backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, marginTop: 8, padding: 12 },
  activityGuideCalendarButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#ffffff', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, marginTop: 10, minHeight: 34, paddingHorizontal: 12 },
  activityGuideCalendarButtonText: { fontSize: 12, fontWeight: '900' },
  activityGuideAddScheduleButton: { alignItems: 'center', borderRadius: 8, borderWidth: 1.2, flexDirection: 'row', gap: 8, justifyContent: 'center', marginTop: 12, minHeight: 44, paddingHorizontal: 12 },
  activityGuideAddScheduleIcon: { alignItems: 'center', borderRadius: 999, height: 24, justifyContent: 'center', width: 24 },
  activityGuideAddScheduleText: { flex: 1, fontSize: 13, fontWeight: '900', textAlign: 'center' },
  activityAiBox: { borderTopColor: '#eef1f5', borderTopWidth: 1, marginTop: 8, paddingTop: 12 },
  activityAiHeaderRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  activityAiInputRow: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, marginTop: 10, padding: 7 },
  activityAiInput: { color: '#141821', flex: 1, fontSize: 13, fontWeight: '800', minHeight: 36, paddingHorizontal: 7, paddingVertical: 0 },
  activityAiButton: { alignItems: 'center', borderRadius: 8, height: 36, justifyContent: 'center', width: 40 },
  activityAiSaveButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, height: 36, justifyContent: 'center', width: 38 },
  activityAiButtonDisabled: { opacity: 0.42 },
  activitySavedList: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 },
  activitySavedItem: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, flexDirection: 'row', maxWidth: '100%', overflow: 'hidden' },
  activitySavedSelect: { alignItems: 'center', flexDirection: 'row', gap: 5, maxWidth: 210, minHeight: 32, paddingLeft: 10, paddingRight: 7 },
  activitySavedText: { color: '#687180', flexShrink: 1, fontSize: 11, fontWeight: '900' },
  activitySavedRemove: { alignItems: 'center', borderLeftColor: '#eef1f5', borderLeftWidth: 1, height: 32, justifyContent: 'center', width: 30 },
  activitySavedRemoveText: { color: '#8a94a3', fontSize: 20, fontWeight: '700', lineHeight: 22 },
  activityAiThinking: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 10, paddingHorizontal: 2 },
  activityAiResult: { borderRadius: 8, borderWidth: 1, marginTop: 10, padding: 11 },
  activityAiResultHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  activityAiResultTitle: { color: '#141821', flex: 1, fontSize: 13, fontWeight: '900', lineHeight: 18 },
  activityAiResultDesc: { color: '#687180', fontSize: 12, fontWeight: '800', lineHeight: 18, marginTop: 7 },
  card: { backgroundColor: '#ffffff', borderColor: '#2fbf71', borderRadius: 8, borderWidth: 1.2, elevation: 2, marginTop: 20, padding: 16, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  detailChartTitleGroup: { flex: 1, minWidth: 0 },
  cardTitle: { color: '#141821', fontSize: 20, fontWeight: '800' },
  cardHint: { color: '#687180', fontSize: 12, marginTop: 5 },
  refreshButton: { backgroundColor: '#e7f6ed', borderColor: '#cfe9da', borderRadius: 8, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 },
  refreshText: { color: '#279b64', fontSize: 12, fontWeight: '800' },
  csvButton: { backgroundColor: '#141821', borderColor: '#141821', borderRadius: 7, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 7 },
  csvButtonText: { color: '#ffffff', fontSize: 11, fontWeight: '900' },
  loadingRow: { alignItems: 'center', flexDirection: 'row', gap: 10, marginTop: 14 },
  mutedText: { color: '#687180', fontSize: 14, lineHeight: 21, marginTop: 10 },
  errorText: { color: '#c84a4a', fontSize: 13, lineHeight: 20, marginTop: 14 },
  flowList: { gap: 12, marginTop: 16 },
  flowSection: { backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, gap: 8, padding: 11 },
  flowSectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  flowSectionTitle: { color: '#141821', fontSize: 14, fontWeight: '900' },
  flowSectionMeta: { color: '#687180', fontSize: 11, fontWeight: '900' },
  flowEmptyText: { color: '#8a94a3', fontSize: 12, fontWeight: '800', lineHeight: 18, paddingVertical: 8 },
  flowChartCard: { backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, elevation: 2, marginTop: 16, paddingHorizontal: 10, paddingTop: 8, paddingBottom: 10, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  flowChartTouchWrap: { height: 180, position: 'relative' },
  flowChartTouchSurface: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  flowChartTooltip: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, marginLeft: -54, minWidth: 108, paddingHorizontal: 11, paddingVertical: 8, position: 'absolute', zIndex: 4 },
  flowChartTooltipValue: { color: '#ffffff', fontSize: 13, fontWeight: '900', marginTop: 2 },
  flowChartTooltipLabel: { color: '#cbd5e1', fontSize: 8, fontWeight: '800' },
  dustFlowNow: { borderRadius: 999, fontSize: 13, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5, position: 'absolute', right: 4, top: 2, zIndex: 2 },
  dustFlowNowUnit: { fontSize: 9, fontWeight: '900' },
  flowChartLegendOverlay: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.86)', borderColor: '#e5e9ef', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, paddingHorizontal: 8, paddingVertical: 4, position: 'absolute', right: 8, top: 8, zIndex: 2 },
  flowChartLegendDot: { borderRadius: 999, height: 7, width: 7 },
  flowChartLegendInlineText: { color: '#687180', fontSize: 9, fontWeight: '900' },
  weatherFlowBlock: { borderTopColor: '#eef1f5', borderTopWidth: 1, marginTop: 10, paddingTop: 12 },
  weatherFlowHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  weatherFlowTitle: { color: '#141821', fontSize: 13, fontWeight: '900' },
  weatherFlowHint: { color: '#8a94a3', fontSize: 10, fontWeight: '800', marginTop: 2 },
  weatherFlowNow: { backgroundColor: '#fff7df', borderRadius: 999, color: '#c58a19', fontSize: 13, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 },
  weatherFlowChartWrap: { height: 104, position: 'relative' },
  weatherFlowTouchSurface: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  weatherFlowTooltip: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, marginLeft: -45, minWidth: 90, paddingHorizontal: 10, paddingVertical: 7, position: 'absolute', zIndex: 4 },
  weatherFlowTooltipValue: { color: '#ffffff', fontSize: 13, fontWeight: '900', marginTop: 2 },
  weatherFlowTooltipLabel: { color: '#cbd5e1', fontSize: 8, fontWeight: '800' },
  flowChartLegendRow: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'center', marginBottom: 3 },
  flowChartLegendText: { backgroundColor: '#eef1f5', borderRadius: 999, color: '#687180', fontSize: 10, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 4 },
  flowChartSummaryRow: { flexDirection: 'row', gap: 8, marginTop: 2 },
  flowChartSummaryPill: { backgroundColor: '#ffffff', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, flex: 1, paddingHorizontal: 10, paddingVertical: 9 },
  flowChartSummaryLabel: { color: '#687180', fontSize: 10, fontWeight: '900', marginBottom: 3 },
  flowChartSummaryValue: { color: '#141821', fontSize: 13, fontWeight: '900' },
  flowRow: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#dce4df', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10 },
  todayFlowRow: { backgroundColor: '#e7f6ed', borderColor: '#2fbf71', borderWidth: 1.5 },
  flowMetricRow: { alignItems: 'center', flexDirection: 'row', gap: 6, marginBottom: 2 },
  flowPhaseBadge: { backgroundColor: '#eef1f5', borderRadius: 999, color: '#687180', fontSize: 10, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 7, paddingVertical: 3 },
  flowMetric: { color: '#279b64', fontSize: 11, fontWeight: '900' },
  flowDate: { color: '#687180', fontSize: 13, fontWeight: '800' },
  flowValueGroup: { alignItems: 'flex-end' },
  flowValue: { color: '#141821', fontSize: 15, fontWeight: '900' },
  flowGrade: { fontSize: 12, fontWeight: '800', marginTop: 2 },
  listHeader: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 12, justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 12 },
  listHeaderAction: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  listChevron: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 30, justifyContent: 'center', width: 30 },
  chevronLine: { backgroundColor: '#141821', borderRadius: 999, height: 2.2, position: 'absolute', width: 8.5 },
  chevronLeft: { transform: [{ translateX: -3 }, { rotate: '45deg' }] },
  chevronRight: { transform: [{ translateX: 3 }, { rotate: '-45deg' }] },
  chevronLeftOpen: { transform: [{ translateX: -3 }, { rotate: '-45deg' }] },
  chevronRightOpen: { transform: [{ translateX: 3 }, { rotate: '45deg' }] },
  listPager: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, elevation: 2, flexDirection: 'row', gap: 10, justifyContent: 'space-between', marginTop: 14, padding: 8, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  listPagerButton: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, height: 42, justifyContent: 'center', width: 46 },
  listPagerButtonDisabled: { backgroundColor: '#eef1f5' },
  listPagerIcon: { color: '#ffffff', fontSize: 28, fontWeight: '900', lineHeight: 30 },
  listPagerIconDisabled: { color: '#aab4ae' },
  listPagerCenter: { alignItems: 'center', flex: 1 },
  listPagerTitle: { color: '#141821', fontSize: 13, fontWeight: '900' },
  listPagerMeta: { color: '#687180', fontSize: 11, fontWeight: '800', marginTop: 3 },
  segmentCard: { backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, elevation: 2, marginTop: 14, padding: 12, shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  sectionLabel: { color: '#687180', fontSize: 12, fontWeight: '900', marginBottom: 8, marginTop: 4 },
  segmentRow: { flexDirection: 'row', gap: 7, marginBottom: 10 },
  segmentButton: { alignItems: 'center', backgroundColor: '#f8f9fa', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flex: 1, paddingVertical: 9 },
  segmentButtonActive: { backgroundColor: '#2fbf71', borderColor: '#2fbf71' },
  segmentText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  segmentTextActive: { color: '#ffffff' },
  metricSelectGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricSelectButton: { backgroundColor: '#f8f9fa', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 9, width: '48%' },
  metricSelectButtonActive: { backgroundColor: '#e7f6ed', borderColor: '#2fbf71' },
  metricSelectCode: { color: '#141821', fontSize: 13, fontWeight: '900' },
  metricSelectLabel: { color: '#687180', fontSize: 13, fontWeight: '900' },
  metricSelectTextActive: { color: '#279b64' },
  chartScroll: { marginTop: 18 },
  chartScrollContent: { paddingRight: 4 },
  chartModeRow: { alignSelf: 'flex-start', backgroundColor: '#f4f6f5', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 5, marginTop: 12, padding: 4 },
  chartModeRowInline: { flexShrink: 0, gap: 3, marginTop: 0, padding: 3 },
  chartModeButton: { alignItems: 'center', borderColor: 'transparent', borderRadius: 7, borderWidth: 1, minWidth: 54, paddingHorizontal: 10, paddingVertical: 6 },
  chartModeButtonInline: { minWidth: 42, paddingHorizontal: 7, paddingVertical: 5 },
  chartModeText: { color: '#687180', fontSize: 11, fontWeight: '900' },
  chartModeTextInline: { fontSize: 10 },
  detailLineChartArea: { backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, elevation: 2, height: 188, overflow: 'visible', position: 'relative', shadowColor: '#141821', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 18 },
  detailLineChartTooltip: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, marginLeft: -54, minWidth: 108, paddingHorizontal: 11, paddingVertical: 8, position: 'absolute', zIndex: 4 },
  detailLineChartTooltipDate: { color: '#cbd5e1', fontSize: 10, fontWeight: '900', marginBottom: 2 },
  detailLineChartTooltipValue: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
  detailLineChartTouchSurface: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  chartArea: { alignItems: 'flex-end', flexDirection: 'row', gap: 4, height: 166, paddingTop: 14 },
  chartAreaCompact: { gap: 12, justifyContent: 'space-between', paddingHorizontal: 6, width: '100%' },
  weatherChartAreaCompact: { gap: 8, justifyContent: 'space-between', paddingHorizontal: 10, width: '100%' },
  chartColumn: { alignItems: 'center', gap: 6, width: 20 },
  chartColumnCompact: { width: 30 },
  weatherChartColumnCompact: { width: 36 },
  chartTrackWrap: { alignItems: 'center', height: 136, justifyContent: 'flex-end', width: '100%' },
  chartTrack: { alignItems: 'center', backgroundColor: '#f1f4f2', borderRadius: 999, height: 118, justifyContent: 'flex-end', overflow: 'hidden', width: '100%' },
  chartBar: { borderRadius: 999, width: '100%' },
  chartBarSelected: { borderWidth: 2, transform: [{ scaleX: 1.18 }] },
  chartSelectedCap: { borderColor: '#ffffff', borderRadius: 999, borderWidth: 2, height: 11, marginBottom: 5, shadowColor: '#141821', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.18, shadowRadius: 4, width: 11 },
  chartDate: { color: '#8a94a3', fontSize: 8, fontWeight: '700', textAlign: 'center', width: 34 },
  chartDateCompact: { fontSize: 9, width: 42 },
  chartSelectedSummary: { alignItems: 'center', borderTopColor: '#eef3ef', borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12, paddingTop: 10 },
  chartSelectedDate: { color: '#687180', fontSize: 12, fontWeight: '900' },
  chartSelectedDivider: { color: '#aab4ae', fontSize: 12, fontWeight: '900' },
  chartSelectedValue: { color: '#141821', fontSize: 12, fontWeight: '900' },
  chartSelectedGrade: { fontSize: 12, fontWeight: '900' },
  dataMetaRow: { borderTopColor: '#eef3ef', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingTop: 12 },
  dataMetaText: { color: '#687180', fontSize: 12, fontWeight: '800' },
  dataList: { gap: 8, marginTop: 14 },
  dataRow: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#b8dcca', borderRadius: 8, borderWidth: 1.3, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 11 },
  dataRowDate: { color: '#141821', fontSize: 14, fontWeight: '900' },
  dataRowGrade: { fontSize: 12, fontWeight: '900', marginTop: 2 },
  dataRowValue: { color: '#141821', fontSize: 14, fontWeight: '900' },
  briefingChatCard: { backgroundColor: 'transparent', borderRadius: 8, borderWidth: 0, marginTop: 6, paddingHorizontal: 0, paddingVertical: 2 },
  quickPromptGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 16 },
  briefingHeaderTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  briefingHeaderIcon: { display: 'none' },
  quickPromptButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 5, paddingHorizontal: 11, paddingVertical: 10, shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 8 },
  quickPromptText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  briefingResetButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 4, justifyContent: 'center', minHeight: 34, paddingHorizontal: 10 },
  briefingResetText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  briefingMessages: { gap: 9, marginTop: 16 },
  briefingBubble: { alignSelf: 'flex-start', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, maxWidth: '92%', paddingHorizontal: 12, paddingVertical: 10, shadowColor: '#141821', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.04, shadowRadius: 10 },
  briefingBubbleUser: { alignSelf: 'flex-end', backgroundColor: '#141821', borderColor: '#141821' },
  briefingBubbleText: { color: '#141821', fontSize: 13, fontWeight: '700', lineHeight: 20 },
  briefingBubbleTextUser: { color: '#ffffff' },
  briefingHighlightGood: { color: '#279b64', fontWeight: '900' },
  briefingHighlightModerate: { color: '#2f80ed', fontWeight: '900' },
  briefingHighlightBad: { color: '#c47b20', fontWeight: '900' },
  briefingHighlightValue: { color: '#141821', fontWeight: '900' },
  briefingHighlightMetric: { color: '#2f80ed', fontWeight: '900' },
  briefingHighlightTime: { color: '#279b64', fontWeight: '900' },
  briefingHighlightFeature: { color: '#687180', fontWeight: '900' },
  typingDots: { alignItems: 'center', flexDirection: 'row', gap: 5, minHeight: 20, paddingHorizontal: 2 },
  typingDot: { backgroundColor: '#687180', borderRadius: 999, height: 7, width: 7 },
  typingStatusRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  typingStatusText: { color: '#687180', fontSize: 12, fontWeight: '800', lineHeight: 18 },
  briefingInputRow: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, marginTop: 16, padding: 8 },
  briefingInput: { color: '#141821', flex: 1, fontSize: 14, fontWeight: '700', minHeight: 38, paddingHorizontal: 6, paddingVertical: 0 },
  briefingSendButton: { alignItems: 'center', backgroundColor: '#2fbf71', borderRadius: 8, justifyContent: 'center', minHeight: 38, minWidth: 42, paddingHorizontal: 12 },
  briefingSendText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  calendarPanel: { backgroundColor: '#ffffff', flex: 1, minHeight: 0, overflow: 'hidden', position: 'relative' },
  calendarFullStage: { bottom: 0, left: 0, minHeight: 0, position: 'absolute', right: 0, top: 0 },
  calendarHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  calendarTodayBadge: { alignItems: 'center', borderRadius: 999, flexDirection: 'row', gap: 5, paddingHorizontal: 11, paddingVertical: 7 },
  calendarTodayText: { fontSize: 12, fontWeight: '900' },
  calendarMonthCard: { backgroundColor: '#ffffff', borderRadius: 0, borderWidth: 0, elevation: 0, flex: 1, minHeight: 0, paddingHorizontal: 0, paddingTop: 10, shadowColor: '#141821', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0, shadowRadius: 0 },
  calendarMonthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, paddingHorizontal: 18 },
  calendarMonthButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, elevation: 1, height: 34, justifyContent: 'center', shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 8, width: 34 },
  calendarMonthTitle: { color: '#141821', fontSize: 19, fontWeight: '900' },
  calendarWeekRow: { flexDirection: 'row', marginBottom: 4, paddingHorizontal: 0 },
  calendarWeekText: { color: '#8a94a3', flex: 1, fontSize: 11, fontWeight: '900', textAlign: 'center' },
  calendarGrid: { borderColor: '#dfe5ec', flex: 1, minHeight: 0 },
  calendarGridWeekRow: { flex: 1, flexDirection: 'row' },
  calendarGridDayFill: { flex: 1, height: '100%' },
  calendarLibraryGrid: { backgroundColor: '#ffffff', borderColor: '#dfe5ec', borderLeftWidth: 1, borderTopWidth: 1, flex: 1, overflow: 'hidden', width: '100%' },
  calendarLibraryMonth: { backgroundColor: 'transparent', flex: 1, margin: 0, padding: 0, width: '100%' },
  calendarDayCell: { alignItems: 'stretch', backgroundColor: '#ffffff', borderBottomWidth: 1, borderColor: '#e6ebf0', borderRadius: 0, borderRightWidth: 1, justifyContent: 'flex-start', minHeight: 0, paddingHorizontal: 4, paddingTop: 8, position: 'relative', width: '14.285%' },
  calendarLibraryDayCell: { width: '100%' },
  calendarBlankDayCell: { backgroundColor: '#fcfdfc' },
  calendarDraftRangeCell: { backgroundColor: '#e7f6ee' },
  calendarDayWeatherRiskBadge: { alignItems: 'center', borderRadius: 999, borderWidth: 1, height: 18, justifyContent: 'center', position: 'absolute', right: 3, top: 3, width: 18, zIndex: 3 },
  calendarRangeAnchorMark: { borderRadius: 999, height: 7, position: 'absolute', right: 3, top: 3, width: 7 },
  calendarDayText: { color: '#141821', fontSize: 13, fontWeight: '900', textAlign: 'center' },
  calendarEventLineStack: { gap: 2, marginTop: 5, minHeight: 42 },
  calendarEventLine: { height: 13, justifyContent: 'center', overflow: 'hidden', paddingHorizontal: 3, zIndex: 2 },
  calendarEventLineSpacer: { height: 13 },
  calendarEventLineText: { color: '#ffffff', fontSize: 8, fontWeight: '900', lineHeight: 11 },
  calendarEventMoreText: { color: '#8a94a3', fontSize: 8, fontWeight: '900', lineHeight: 10, paddingHorizontal: 2 },
  calendarSheetBackdrop: { backgroundColor: '#ffffff', flex: 1, position: 'relative' },
  calendarSheetKeyboardArea: { flex: 1 },
  calendarEditorHeader: { alignItems: 'center', backgroundColor: '#ffffff', flexDirection: 'row', justifyContent: 'space-between', minHeight: 88, paddingHorizontal: 18, paddingTop: 24 },
  calendarEditorHeaderButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 },
  calendarEditorHeaderButtonDisabled: { opacity: 0.62 },
  calendarEditorHeaderTitle: { color: '#141821', fontSize: 21, fontWeight: '900' },
  calendarSheetDimLayer: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  calendarSheetScroll: { alignSelf: 'stretch', flex: 1 },
  calendarSheetScrollContent: { flexGrow: 1, paddingBottom: 110, paddingHorizontal: 18, paddingTop: 6 },
  calendarSheet: { alignSelf: 'stretch', backgroundColor: '#ffffff', borderRadius: 0, borderWidth: 0, elevation: 0, paddingHorizontal: 0, paddingTop: 0, shadowColor: '#141821', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0, shadowRadius: 0 },
  calendarSheetHandle: { alignSelf: 'center', backgroundColor: '#d9dee5', borderRadius: 999, height: 4, marginBottom: 10, width: 46 },
  calendarSheetTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 12, minHeight: 68 },
  calendarSheetTitleInput: { color: '#141821', flex: 1, fontSize: 22, fontWeight: '900', paddingVertical: 0 },
  calendarColorDot: { borderRadius: 999, height: 14, width: 14 },
  calendarSheetDivider: { backgroundColor: '#eef1f5', height: 1 },
  calendarSheetRow: { alignItems: 'center', flexDirection: 'row', gap: 16, minHeight: 64 },
  calendarSheetDateTimeBlock: { alignItems: 'flex-start', flexDirection: 'row', gap: 16, paddingVertical: 16 },
  calendarSheetTimeGroup: { flex: 1, gap: 8, paddingVertical: 10 },
  calendarSheetDateText: { color: '#687180', fontSize: 12, fontWeight: '900', marginBottom: 3 },
  calendarSheetDateFocus: { alignItems: 'center', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, marginVertical: 12, minHeight: 62, paddingHorizontal: 12, paddingVertical: 10 },
  calendarSheetDateFocusBody: { flex: 1, minWidth: 0 },
  calendarSheetDateFocusLabel: { fontSize: 11, fontWeight: '900', marginBottom: 3 },
  calendarSheetDateFocusValue: { color: '#141821', fontSize: 17, fontWeight: '900' },
  calendarSheetTimeInput: { color: '#141821', fontSize: 18, fontWeight: '900', minWidth: 70, paddingVertical: 0 },
  calendarSheetRowAction: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 10, justifyContent: 'space-between', minHeight: 44 },
  calendarClockGroup: { gap: 8 },
  calendarClockDisplayRow: { alignItems: 'center', backgroundColor: '#f5faf7', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 6, padding: 4 },
  calendarClockDisplayButton: { alignItems: 'center', backgroundColor: 'transparent', borderColor: 'transparent', borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 10, paddingVertical: 7 },
  calendarClockDisplayLabel: { color: '#8a94a3', fontSize: 10, fontWeight: '900' },
  calendarClockDisplayValue: { color: '#141821', fontSize: 20, fontWeight: '900' },
  calendarClockClearButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9eee2', borderRadius: 999, borderWidth: 1, height: 28, justifyContent: 'center', width: 28 },
  calendarDigitalClockBody: { alignItems: 'center', backgroundColor: '#f7faf8', borderRadius: 8, marginTop: 0, paddingHorizontal: 10, paddingVertical: 8 },
  calendarDigitalTimeRow: { alignItems: 'center', alignSelf: 'stretch', flexDirection: 'row', gap: 8, justifyContent: 'center' },
  calendarDigitalStepColumn: { alignItems: 'center', flex: 1, gap: 3 },
  calendarDigitalStepButton: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: '#ffffff', borderColor: '#d9eee2', borderRadius: 999, borderWidth: 1, height: 25, justifyContent: 'center' },
  calendarDigitalNumberButton: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: '#ffffff', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 58, paddingVertical: 4 },
  calendarDigitalUnitLabel: { color: '#8a94a3', fontSize: 10, fontWeight: '900' },
  calendarDigitalTimeNumber: { color: '#141821', fontSize: 32, fontWeight: '900', lineHeight: 36, textAlign: 'center' },
  calendarDigitalColon: { color: '#8a94a3', fontSize: 28, fontWeight: '900', paddingTop: 18 },
  calendarDateTimePickerGroup: { flex: 1, gap: 8 },
  calendarDateTimeSummaryRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  calendarDateTimeSummaryCard: { backgroundColor: '#ffffff', borderColor: '#edf1f5', borderRadius: 8, borderWidth: 1, flex: 1, minHeight: 84, paddingHorizontal: 10, paddingVertical: 9 },
  calendarDateTimeSummaryLabel: { color: '#8a94a3', fontSize: 10, fontWeight: '900', marginBottom: 4 },
  calendarDateTimeSummaryDate: { color: '#687180', fontSize: 11, fontWeight: '900' },
  calendarDateTimeSummaryTime: { color: '#141821', fontSize: 25, fontWeight: '900', marginTop: 2 },
  calendarDateWheel: { alignItems: 'center', backgroundColor: '#f7faf8', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 5, justifyContent: 'space-between', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 10, position: 'relative' },
  calendarDateWheelHighlight: { borderRadius: 8, height: 42, left: 8, opacity: 0.84, position: 'absolute', right: 8, top: 36 },
  calendarDateWheelColumn: { alignItems: 'center', flex: 1, gap: 3, minWidth: 0 },
  calendarDateWheelColumnDisabled: { opacity: 0.45 },
  calendarDateWheelStep: { alignItems: 'center', alignSelf: 'stretch', height: 24, justifyContent: 'center' },
  calendarDateWheelValue: { alignItems: 'center', alignSelf: 'stretch', borderRadius: 8, justifyContent: 'center', minHeight: 42, paddingHorizontal: 2 },
  calendarDateWheelLabel: { color: '#8a94a3', fontSize: 9, fontWeight: '900' },
  calendarDateWheelText: { color: '#141821', fontSize: 18, fontWeight: '900', lineHeight: 23, textAlign: 'center' },
  calendarSheetTextInput: { color: '#141821', flex: 1, fontSize: 16, fontWeight: '800', minHeight: 44, paddingVertical: 0 },
  calendarLocationSuggestionList: { backgroundColor: '#f7faf8', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, gap: 2, marginBottom: 10, marginLeft: 36, overflow: 'hidden' },
  calendarLocationSuggestionItem: { paddingHorizontal: 12, paddingVertical: 10 },
  calendarLocationSuggestionTitle: { color: '#141821', fontSize: 13, fontWeight: '900' },
  calendarLocationSuggestionMeta: { color: '#8a94a3', fontSize: 11, fontWeight: '800', marginTop: 2 },
  calendarLocationSearchMessage: { color: '#8a94a3', fontSize: 12, fontWeight: '800', marginBottom: 10, marginLeft: 36, marginTop: -2 },
  calendarLocationMapButton: { alignItems: 'center', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 4, justifyContent: 'center', minHeight: 34, paddingHorizontal: 10 },
  calendarLocationMapButtonText: { fontSize: 12, fontWeight: '900' },
  calendarLocationMapSelectButton: { alignItems: 'center', backgroundColor: '#fbfcfb', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 10, justifyContent: 'space-between', minHeight: 48, paddingHorizontal: 12 },
  calendarLocationMapSelectTextGroup: { flex: 1, minWidth: 0 },
  calendarLocationMapSelectLabel: { color: '#8a94a3', fontSize: 13, fontWeight: '900' },
  calendarLocationMapSelectValue: { fontSize: 15, fontWeight: '900' },
  calendarMapPickerBackdrop: { backgroundColor: '#ffffff', flex: 1 },
  calendarMapPickerHeader: { alignItems: 'center', backgroundColor: '#ffffff', borderBottomColor: '#eef1f5', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 76, paddingHorizontal: 18, paddingBottom: 10 },
  calendarMapPickerTitleGroup: { alignItems: 'center', flex: 1, minWidth: 0 },
  calendarMapPickerSubText: { color: '#8a94a3', fontSize: 11, fontWeight: '800', marginTop: 3, textAlign: 'center' },
  calendarMapPickerSearchWrap: { left: 14, position: 'absolute', right: 14, top: 108, zIndex: 5 },
  calendarMapPickerSearchBar: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.97)', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 8, minHeight: 46, paddingHorizontal: 14, shadowColor: '#141821', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 12 },
  calendarMapPickerSearchInput: { color: '#141821', flex: 1, fontSize: 15, fontWeight: '800', minHeight: 42, padding: 0 },
  calendarMapPickerSearchResults: { backgroundColor: 'rgba(255,255,255,0.98)', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, marginTop: 8, overflow: 'hidden', shadowColor: '#141821', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.06, shadowRadius: 12 },
  calendarMapPickerSearchResultItem: { borderBottomColor: '#eef1f5', borderBottomWidth: 1, paddingHorizontal: 13, paddingVertical: 10 },
  calendarMapPickerSearchResultTitle: { color: '#141821', fontSize: 14, fontWeight: '900' },
  calendarMapPickerSearchResultMeta: { color: '#687180', fontSize: 12, fontWeight: '700', marginTop: 3 },
  calendarMapPickerSearchMessage: { backgroundColor: 'rgba(255,255,255,0.96)', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, color: '#687180', fontSize: 12, fontWeight: '800', marginTop: 8, paddingHorizontal: 13, paddingVertical: 11 },
  calendarMapPickerWebView: { backgroundColor: '#f9faf9', flex: 1 },
  calendarMapPickerConfirmBar: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.98)', borderTopColor: '#d9dee5', borderTopWidth: 1, bottom: 0, flexDirection: 'row', gap: 12, left: 0, paddingHorizontal: 16, paddingTop: 12, position: 'absolute', right: 0, zIndex: 6 },
  calendarMapPickerConfirmTextGroup: { flex: 1, minWidth: 0 },
  calendarMapPickerConfirmTitle: { color: '#141821', fontSize: 15, fontWeight: '900' },
  calendarMapPickerConfirmMeta: { color: '#687180', fontSize: 12, fontWeight: '800', marginTop: 3 },
  calendarMapPickerConfirmButton: { alignItems: 'center', borderRadius: 999, justifyContent: 'center', minHeight: 42, paddingHorizontal: 15 },
  calendarMapPickerConfirmButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  calendarSheetRowText: { color: '#141821', flex: 1, fontSize: 16, fontWeight: '800' },
  calendarRepeatBlock: { flex: 1, gap: 9, paddingVertical: 10 },
  calendarRepeatOptionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  calendarRepeatOption: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#e5e9ef', borderRadius: 999, borderWidth: 1, minHeight: 34, minWidth: 62, paddingHorizontal: 11, justifyContent: 'center' },
  calendarRepeatOptionText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarActivityOptionGrid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 7, paddingVertical: 10 },
  calendarActivityOption: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#e5e9ef', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, minHeight: 34, minWidth: 72, paddingHorizontal: 10, justifyContent: 'center' },
  calendarActivityOptionText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarRepeatHint: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarWeekdayPicker: { flexDirection: 'row', gap: 5 },
  calendarWeekdayChip: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#e5e9ef', borderRadius: 999, borderWidth: 1, height: 32, justifyContent: 'center', width: 32 },
  calendarWeekdayChipText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarRepeatEndButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, minHeight: 38, paddingHorizontal: 10 },
  calendarRepeatEndLabel: { color: '#8a94a3', fontSize: 11, fontWeight: '900' },
  calendarRepeatEndValue: { fontSize: 12, fontWeight: '900' },
  calendarRepeatDateWheel: { alignItems: 'center', backgroundColor: '#f7faf8', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 5, justifyContent: 'space-between', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 10, position: 'relative' },
  calendarMemoRow: { alignItems: 'flex-start', paddingTop: 18, paddingBottom: 18 },
  calendarMemoInput: { minHeight: 92, paddingTop: 0, paddingBottom: 10 },
  calendarEditorSwitch: { alignItems: 'flex-start', backgroundColor: '#d9dee5', borderRadius: 999, height: 30, justifyContent: 'center', paddingHorizontal: 3, width: 52 },
  calendarEditorSwitchThumb: { backgroundColor: '#ffffff', borderRadius: 999, height: 24, width: 24 },
  calendarEditorSwitchThumbActive: { transform: [{ translateX: 22 }] },
  calendarSheetActionBar: { alignSelf: 'center', alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, elevation: 9, flexDirection: 'row', marginTop: 12, minHeight: 54, overflow: 'hidden', shadowColor: '#141821', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.16, shadowRadius: 18 },
  calendarSheetActionButton: { alignItems: 'center', justifyContent: 'center', minHeight: 54, minWidth: 112, paddingHorizontal: 22 },
  calendarSheetActionDivider: { backgroundColor: '#d9dee5', height: 24, width: 1 },
  calendarSheetCancelText: { color: '#687180', fontSize: 15, fontWeight: '900' },
  calendarSheetSaveText: { fontSize: 15, fontWeight: '900' },
  calendarEditorCard: { backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1.2, elevation: 2, gap: 10, padding: 14, shadowColor: '#141821', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.05, shadowRadius: 16 },
  calendarListCard: { backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1.2, elevation: 2, gap: 8, padding: 14, shadowColor: '#141821', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.04, shadowRadius: 14 },
  calendarSelectionSheet: { backgroundColor: 'rgba(255,255,255,0.96)', borderRadius: 8, borderWidth: 1.2, bottom: 78, elevation: 7, gap: 10, left: 0, marginHorizontal: 0, maxHeight: 245, paddingHorizontal: 14, paddingTop: 8, paddingBottom: 14, position: 'absolute', right: 0, shadowColor: '#141821', shadowOffset: { width: 0, height: -6 }, shadowOpacity: 0.08, shadowRadius: 18, zIndex: 4 },
  calendarDaySheet: { backgroundColor: 'rgba(255,255,255,0.97)', borderTopColor: '#d9eee2', borderTopWidth: 1.2, bottom: 0, elevation: 0, gap: 10, left: 0, maxHeight: 330, paddingHorizontal: 14, paddingTop: 0, paddingBottom: 14, position: 'absolute', right: 0, shadowColor: '#141821', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0, shadowRadius: 0, zIndex: 4 },
  calendarDaySheetDragArea: { alignItems: 'center', minHeight: 30, justifyContent: 'center' },
  calendarDaySheetList: { flex: 1, minHeight: 0 },
  calendarDaySheetListExpanded: { flex: 1, maxHeight: '100%' },
  calendarDaySheetListContent: { paddingBottom: 18 },
  calendarSelectionHandle: { alignSelf: 'center', backgroundColor: '#d9dee5', borderRadius: 999, height: 4, marginBottom: 4, width: 44 },
  calendarSelectionTopRow: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  calendarSelectionTitleGroup: { flex: 1, minWidth: 0 },
  calendarSelectionDateText: { color: '#141821', fontSize: 20, fontWeight: '900' },
  calendarSelectionSubText: { color: '#8a94a3', fontSize: 12, fontWeight: '900', marginTop: 3 },
  calendarSelectionWeatherRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
  calendarWeatherRiskRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: -2 },
  calendarWeatherRiskPill: { alignItems: 'center', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 4, minHeight: 28, paddingHorizontal: 9 },
  calendarWeatherRiskText: { fontSize: 11, fontWeight: '900', lineHeight: 14 },
  calendarSelectionMetric: { color: '#687180', fontSize: 13, fontWeight: '900' },
  calendarMetricChip: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, minHeight: 34, paddingHorizontal: 9 },
  calendarMetricChipLabel: { color: '#8a94a3', fontSize: 9, fontWeight: '900', lineHeight: 11 },
  calendarMetricChipValue: { fontSize: 11, fontWeight: '900', lineHeight: 14 },
  calendarSelectionDivider: { backgroundColor: '#eef1f5', height: 1 },
  calendarSelectionEmptyRow: { alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 54 },
  calendarSelectionEmptyBar: { borderRadius: 999, height: 32, opacity: 0.75, width: 4 },
  calendarSelectionEmptyTitle: { color: '#687180', fontSize: 15, fontWeight: '900' },
  calendarFloatingAddButton: { alignItems: 'center', borderRadius: 999, bottom: 20, elevation: 7, height: 54, justifyContent: 'center', position: 'absolute', right: 18, shadowColor: '#279b64', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.18, shadowRadius: 14, width: 54, zIndex: 6 },
  calendarEditorSaveFab: { alignItems: 'center', borderRadius: 999, bottom: 24, elevation: 7, height: 56, justifyContent: 'center', position: 'absolute', right: 20, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.18, shadowRadius: 14, width: 56, zIndex: 8 },
  calendarSectionTitle: { color: '#141821', fontSize: 17, fontWeight: '900' },
  calendarInput: { backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, color: '#141821', fontSize: 13, fontWeight: '800', minHeight: 44, paddingHorizontal: 12 },
  calendarInputGrid: { flexDirection: 'row', gap: 8 },
  calendarInputHalf: { flex: 1 },
  calendarSelectedDateText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarSegmentRow: { flexDirection: 'row', gap: 8 },
  calendarSegmentButton: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 42 },
  calendarSegmentText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  calendarCheckRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 36 },
  calendarCheckText: { color: '#687180', flex: 1, fontSize: 12, fontWeight: '800' },
  calendarAddButton: { alignItems: 'center', borderRadius: 8, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44 },
  calendarAddText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  calendarEventRow: { alignItems: 'center', borderTopColor: '#eef1f5', borderTopWidth: 1, flexDirection: 'row', gap: 10, minHeight: 66, paddingVertical: 9 },
  calendarEventIcon: { alignItems: 'center', borderRadius: 8, height: 36, justifyContent: 'center', width: 36 },
  calendarEventBody: { flex: 1, minWidth: 0 },
  calendarEventTitle: { color: '#141821', fontSize: 14, fontWeight: '900' },
  calendarEventMeta: { color: '#687180', fontSize: 11, fontWeight: '800', lineHeight: 16, marginTop: 3 },
  calendarEventMemo: { color: '#8a94a3', fontSize: 11, fontWeight: '800', lineHeight: 16, marginTop: 2 },
  calendarGuideBadge: { borderRadius: 999, fontSize: 11, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 5 },
  calendarBadgeStack: { alignItems: 'flex-end', gap: 4 },
  calendarIconButton: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 32, justifyContent: 'center', width: 32 },
  calendarRemoveButton: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, height: 32, justifyContent: 'center', width: 32 },
  calendarEmptyBox: { backgroundColor: '#fbfcfb', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, gap: 8, padding: 12 },
  accountHero: { backgroundColor: 'transparent', borderRadius: 8, borderWidth: 0, marginTop: 8, paddingHorizontal: 0, paddingVertical: 4 },
  accountHeroTopRow: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  accountHeroIcon: { alignItems: 'center', borderRadius: 8, height: 42, justifyContent: 'center', width: 42 },
  accountName: { color: '#141821', fontSize: 28, fontWeight: '900', marginTop: 10 },
  accountMeta: { color: '#687180', fontSize: 13, fontWeight: '800', marginTop: 6 },
  accountMessage: { color: '#687180', fontSize: 13, fontWeight: '800', lineHeight: 19, marginTop: 4 },
  locationGate: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: 28 },
  locationGateTitle: { color: '#141821', fontSize: 22, fontWeight: '900', marginTop: 18 },
  locationGateText: { color: '#687180', fontSize: 14, fontWeight: '800', lineHeight: 21, marginTop: 8, textAlign: 'center' },
  locationGateButton: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, justifyContent: 'center', marginTop: 18, minHeight: 44, paddingHorizontal: 18 },
  locationGateButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  locationButton: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', marginTop: 14, minHeight: 42, paddingHorizontal: 12, shadowColor: '#141821', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 8 },
  locationButtonText: { color: '#279b64', fontSize: 13, fontWeight: '900' },
  notificationRow: { alignItems: 'center', borderBottomColor: '#eef1f5', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 48 },
  notificationRowDisabled: { opacity: 0.58 },
  notificationLabel: { color: '#141821', fontSize: 14, fontWeight: '900' },
  notificationThresholdRow: { alignItems: 'center', borderBottomColor: '#eef1f5', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 58, paddingVertical: 8 },
  notificationThresholdTextGroup: { flex: 1, paddingRight: 10 },
  notificationThresholdHint: { color: '#8a94a3', fontSize: 11, fontWeight: '800', marginTop: 3 },
  notificationThresholdControl: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  notificationThresholdUnit: { color: '#687180', fontSize: 11, fontWeight: '900' },
  bottomToast: { alignItems: 'center', alignSelf: 'center', backgroundColor: 'rgba(20, 24, 33, 0.68)', borderRadius: 8, bottom: 88, maxWidth: '86%', paddingHorizontal: 14, paddingVertical: 11, position: 'absolute', zIndex: 30 },
  bottomToastText: { color: '#ffffff', fontSize: 13, fontWeight: '900', lineHeight: 18, textAlign: 'center' },
  emptyFavoriteBox: { alignItems: 'flex-start', backgroundColor: '#f7faf8', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1.2, gap: 3, marginTop: 14, padding: 13 },
  favoriteList: { gap: 9, marginTop: 14 },
  favoriteRow: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#d9dee5', borderRadius: 8, borderWidth: 1.2, flexDirection: 'row', gap: 10, padding: 11 },
  favoriteRowActive: { backgroundColor: '#f0fbf5', borderColor: '#2fbf71' },
  favoriteSelectArea: { flex: 1 },
  favoriteTitle: { color: '#141821', fontSize: 15, fontWeight: '900' },
  favoriteTitleActive: { color: '#279b64' },
  favoriteMeta: { color: '#687180', fontSize: 11, fontWeight: '800', marginTop: 3 },
  favoriteRemoveButton: { alignItems: 'center', borderColor: '#c5ccd6', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 4, justifyContent: 'center', minHeight: 34, paddingHorizontal: 10 },
  favoriteRemoveText: { color: '#687180', fontSize: 11, fontWeight: '900' },
  favoritePager: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'center', marginTop: 12 },
  favoritePagerButton: { alignItems: 'center', backgroundColor: '#141821', borderRadius: 8, height: 34, justifyContent: 'center', width: 42 },
  favoritePagerButtonDisabled: { backgroundColor: '#eef1f5' },
  favoritePagerIcon: { color: '#ffffff', fontSize: 24, fontWeight: '900', lineHeight: 26 },
  favoritePagerIconDisabled: { color: '#aab4ae' },
  favoritePagerText: { color: '#141821', fontSize: 13, fontWeight: '900', minWidth: 44, textAlign: 'center' },
  fullMapContainer: { backgroundColor: '#f9faf9', flex: 1 },
  fullMapErrorBanner: { alignItems: 'center', backgroundColor: '#fff7f5', borderColor: '#f0c3bb', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, left: 16, paddingHorizontal: 12, paddingVertical: 10, position: 'absolute', right: 16, top: 104, zIndex: 30 },
  fullMapErrorText: { color: '#9d332a', flex: 1, fontSize: 12, fontWeight: '800', lineHeight: 17 },
  fullMapRetryButton: { backgroundColor: '#c84a4a', borderRadius: 7, paddingHorizontal: 10, paddingVertical: 7 },
  fullMapRetryText: { color: '#ffffff', fontSize: 12, fontWeight: '900' },
  fullMapWebView: { flex: 1, backgroundColor: '#f9faf9' },
  mapSearchBackInlineButton: { alignItems: 'center', backgroundColor: '#f3f6f8', borderRadius: 999, height: 34, justifyContent: 'center', marginRight: 2, width: 34 },
  mapSearchBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderColor: '#d9eee2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    left: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    position: 'absolute',
    right: 14,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    top: 10,
    zIndex: 2,
  },
  mapSearchIcon: { color: '#279b64', fontSize: 18, fontWeight: '900' },
  mapSearchInput: { color: '#141821', flex: 1, fontSize: 15, fontWeight: '700', minHeight: 34, padding: 0 },
  mapSearchGpsButton: { alignItems: 'center', backgroundColor: '#f3f6f8', borderRadius: 999, height: 34, justifyContent: 'center', marginLeft: 2, width: 34 },
  mapMarkerModeIconButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.96)', borderRadius: 999, borderWidth: 1, height: 46, justifyContent: 'center', position: 'absolute', right: 14, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 12, top: 74, width: 46, zIndex: 3 },
  mapSearchMessage: { backgroundColor: 'rgba(255,255,255,0.94)', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, color: '#687180', fontSize: 12, fontWeight: '800', left: 14, paddingHorizontal: 12, paddingVertical: 8, position: 'absolute', top: 74, zIndex: 2 },
  searchSuggestions: { backgroundColor: 'rgba(255,255,255,0.97)', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, left: 14, overflow: 'hidden', position: 'absolute', right: 14, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 12, top: 58, zIndex: 3 },
  searchSuggestionItem: { borderBottomColor: '#eef3ef', borderBottomWidth: 1, paddingHorizontal: 14, paddingVertical: 10 },
  searchSuggestionTitle: { color: '#141821', fontSize: 14, fontWeight: '900' },
  searchSuggestionMeta: { color: '#687180', fontSize: 12, marginTop: 3 },
  mapSearchOverlay: { backgroundColor: '#f7fbf9', bottom: 0, left: 0, paddingHorizontal: 18, paddingTop: 14, position: 'absolute', right: 0, top: 0, zIndex: 8 },
  mapSearchOverlayHeader: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#d9dee5', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 8, minHeight: 52, paddingHorizontal: 10, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 12 },
  mapSearchBackButton: { alignItems: 'center', backgroundColor: '#f3f6f8', borderRadius: 999, height: 34, justifyContent: 'center', width: 34 },
  mapSearchOverlayInput: { color: '#141821', flex: 1, fontSize: 16, fontWeight: '800', minHeight: 44, padding: 0 },
  mapSearchOverlayGpsButton: { alignItems: 'center', backgroundColor: '#f3f6f8', borderRadius: 999, height: 34, justifyContent: 'center', width: 34 },
  mapSearchModeRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  mapSearchModePill: { backgroundColor: '#2f80ed', borderRadius: 999, color: '#ffffff', fontSize: 13, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 14, paddingVertical: 9 },
  mapSearchModePillMuted: { backgroundColor: '#eef1f5', color: '#687180' },
  mapSearchClearButton: { paddingHorizontal: 4, paddingVertical: 8 },
  mapSearchClearText: { color: '#687180', fontSize: 12, fontWeight: '900' },
  mapSearchOverlayList: { backgroundColor: '#ffffff', borderColor: '#e5e9ef', borderRadius: 8, borderWidth: 1, marginTop: 12, overflow: 'hidden', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 12 },
  mapSearchOverlayItem: { alignItems: 'center', borderBottomColor: '#eef1f5', borderBottomWidth: 1, flexDirection: 'row', gap: 8, paddingRight: 8 },
  mapSearchOverlaySelect: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 11, paddingHorizontal: 12, paddingVertical: 14 },
  mapSearchOverlayPin: { color: '#687180', fontSize: 20, fontWeight: '900', width: 24 },
  mapSearchOverlayTextGroup: { flex: 1 },
  mapSearchOverlayTitle: { color: '#141821', fontSize: 15, fontWeight: '900' },
  mapSearchOverlayMeta: { color: '#687180', fontSize: 12, fontWeight: '700', lineHeight: 17, marginTop: 3 },
  mapSearchRemoveButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 36 },
  mapSearchRemoveText: { color: '#8a94a3', fontSize: 28, fontWeight: '500', lineHeight: 30 },
  mapSearchEmptyText: { color: '#8a94a3', fontSize: 13, fontWeight: '800', lineHeight: 20, padding: 16 },
  mapLoadingBadge: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.95)', borderColor: '#d9eee2', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, left: 14, paddingHorizontal: 12, paddingVertical: 9, position: 'absolute', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.07, shadowRadius: 12, top: 82, zIndex: 2 },
  mapLoadingText: { color: '#687180', fontSize: 12, fontWeight: '800' },
  stationSheet: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderColor: '#e5e9ef',
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    paddingBottom: 14,
    paddingHorizontal: 16,
    paddingTop: 4,
    position: 'absolute',
    right: 0,
    shadowColor: '#141821',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    zIndex: 4,
  },
  stationDragArea: { alignItems: 'center', paddingBottom: 8, paddingTop: 4 },
  stationSheetHandle: { alignSelf: 'center', backgroundColor: '#d5ded8', borderRadius: 999, height: 4, width: 38 },
  stationSheetHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  stationTitleGroup: { flex: 1 },
  stationEyebrow: { color: '#279b64', fontSize: 11, fontWeight: '900', marginBottom: 3 },
  stationTitle: { color: '#141821', fontSize: 22, fontWeight: '900' },
  stationFavoriteButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 34 },
  stationFavoriteButtonActive: {},
  stationFavoriteText: { color: '#aab4ae', fontSize: 25, fontWeight: '900', marginTop: -2 },
  stationFavoriteTextActive: { color: '#e2b93b' },
  stationTime: { color: '#687180', fontSize: 12, fontWeight: '700', marginTop: 4 },
  stationAddress: { color: '#687180', fontSize: 12, fontWeight: '600', marginTop: 3 },
  stationMainRow: { alignItems: 'center', borderBottomColor: '#e5e9ef', borderBottomWidth: 1, flexDirection: 'row', gap: 14, marginTop: 12, paddingBottom: 12 },
  stationValueCircle: { alignItems: 'center', borderRadius: 999, height: 54, justifyContent: 'center', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.32, shadowRadius: 12, width: 54 },
  stationValueCircleText: { color: '#ffffff', fontSize: 21, fontWeight: '900' },
  stationGauge: { flex: 1, gap: 8 },
  stationGaugeHead: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  stationGaugeLabel: { color: '#141821', fontSize: 13, fontWeight: '900' },
  stationGaugeGrade: { fontSize: 12, fontWeight: '900' },
  stationGaugeTrack: { backgroundColor: '#eef1f5', borderRadius: 999, height: 8, overflow: 'hidden' },
  stationGaugeFill: { borderRadius: 999, height: '100%' },
  stationWeatherRow: { alignItems: 'center', borderBottomColor: '#e5e9ef', borderBottomWidth: 1, flexDirection: 'row', gap: 8, paddingBottom: 10, paddingTop: 10 },
  stationWeatherIconBox: { alignItems: 'center', backgroundColor: '#fff7df', borderRadius: 999, height: 28, justifyContent: 'center', width: 28 },
  stationWeatherText: { color: '#687180', flex: 1, fontSize: 12, fontWeight: '800' },
  stationWeatherSummaryRow: { alignItems: 'center', borderBottomColor: '#e5e9ef', borderBottomWidth: 1, flexDirection: 'row', gap: 12, marginTop: 12, paddingBottom: 12 },
  stationWeatherHero: { alignItems: 'center', backgroundColor: '#fbfcfb', borderColor: '#eef1f5', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 12, marginTop: 12, padding: 12 },
  stationWeatherHeroIcon: { alignItems: 'center', borderRadius: 999, height: 52, justifyContent: 'center', width: 52 },
  stationWeatherHeroText: { flex: 1 },
  stationWeatherHeroLabel: { color: '#687180', fontSize: 11, fontWeight: '900' },
  stationWeatherHeroTitle: { color: '#141821', fontSize: 30, fontWeight: '900', lineHeight: 34 },
  stationWeatherHeroCondition: { color: '#687180', fontSize: 14, fontWeight: '900' },
  stationWeatherHeroMeta: { color: '#687180', fontSize: 11, fontWeight: '800', marginTop: 2 },
  stationWeatherHeroBadge: { backgroundColor: '#f8fffb', borderRadius: 999, fontSize: 13, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6 },
  stationWeatherQuickGrid: { flexDirection: 'row', gap: 8, marginTop: 10 },
  stationWeatherQuickItem: { backgroundColor: '#ffffff', borderColor: '#eef1f5', borderRadius: 8, borderWidth: 1, flex: 1, paddingHorizontal: 9, paddingVertical: 8 },
  stationWeatherQuickLabel: { color: '#687180', fontSize: 10, fontWeight: '900' },
  stationWeatherQuickValue: { color: '#141821', fontSize: 18, fontWeight: '900', marginTop: 3 },
  stationWeatherQuickUnit: { color: '#8a94a3', fontSize: 10, fontWeight: '800', marginTop: 1 },
  stationMetricGrid: { flexDirection: 'row', gap: 8, marginTop: 12 },
  stationMetric: { backgroundColor: '#f8fffb', borderColor: '#cfdcd5', borderRadius: 8, borderWidth: 1, flex: 1, paddingHorizontal: 9, paddingVertical: 8 },
  stationMetricLabel: { color: '#687180', fontSize: 11, fontWeight: '900' },
  stationMetricValue: { color: '#141821', fontSize: 18, fontWeight: '900', marginTop: 3 },
  stationMetricUnit: { color: '#687180', fontSize: 11, marginTop: 1 },
  stationMetricGrade: { fontSize: 11, fontWeight: '900', marginTop: 4 },
  tabBar: { backgroundColor: '#ffffff', borderTopColor: '#cfe9da', borderTopWidth: 1, flexDirection: 'row', paddingBottom: 10, paddingHorizontal: 8, paddingTop: 8 },
  tabItem: { alignItems: 'center', borderRadius: 8, flex: 1, gap: 3, justifyContent: 'center', minHeight: 50 },
  activeTabItem: { backgroundColor: '#e7f6ed' },
  tabText: { color: '#687180', fontSize: 11, fontWeight: '900' },
  activeTabText: { color: '#279b64' },
});
