"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and limitations, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv  # 추가
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_value(name, default=''):
    value = os.environ.get(name)
    return value.strip() if value and value.strip() else default

def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')

def env_list(name, default=None):
    value = os.environ.get(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]

DB_USER = env_value('DB_USER', 'root')
DB_PASS = env_value('DB_PASS', 'mysql')
DB_HOST = env_value('DB_HOST', '127.0.0.1')
DB_PORT = env_value('DB_PORT', '3306')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

if not SECRET_KEY and not DEBUG:
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False')

DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'vmv-lab.com',
    'www.vmv-lab.com',
    'dust.vmv-lab.com',
]
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS)

DEFAULT_LOGGING = {
    'version': 1,
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',          # 템플릿 폴더
    'api',          # api 서비스 폴더
    'corsheaders',  # CORS
    'dust',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'dust.test_access.AppTestTokenMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # React build/index.html을 템플릿으로 서빙하기 위해 build 폴더 추가
        'DIRS': [
            os.path.join(BASE_DIR, 'build'),
            'app',
            'api',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env_value('DB_NAME', 'sys'),
        'USER': DB_USER,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'app.Users'

# 배포 시 실제 도메인으로 변경 (예: 'https://yourdomain.com')
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:3001',
    'http://localhost:3001',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://vmv-lab.com',
    'https://www.vmv-lab.com',
    'https://dust.vmv-lab.com',
]
# 환경변수로 추가 도메인 지정 가능 (예: CSRF_EXTRA_ORIGIN=https://yourdomain.com,http://localhost:3000)
_extra_origins = [origin.strip() for origin in os.environ.get('CSRF_EXTRA_ORIGIN', '').split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS.extend(_extra_origins)

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://vmv-lab.com",
    "https://www.vmv-lab.com",
    "https://dust.vmv-lab.com",
]
# 환경변수로 추가 CORS 도메인 지정 가능 (예: CORS_EXTRA_ORIGIN=https://yourdomain.com,http://localhost:3000)
_extra_cors_origins = [origin.strip() for origin in os.environ.get('CORS_EXTRA_ORIGIN', '').split(',') if origin.strip()]
CORS_ALLOWED_ORIGINS.extend(_extra_cors_origins)

CORS_ALLOW_CREDENTIALS = True

# 쿠키 설정 (배포 시 HTTPS 사용하면 SESSION_COOKIE_SECURE=True로 변경)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = env_bool('COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('COOKIE_SECURE', not DEBUG)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(env_value('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

# Session 만료 시간 설정 (10시간)
SESSION_COOKIE_AGE = 36000


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # React build 정적 파일 (JS, CSS)
    os.path.join(BASE_DIR, 'build', 'static'),
]
# collectstatic 결과물 경로 (배포 시 사용)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
